### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by phoe** [nasa/pvslib#6]
#3 was closed but the license file was not added nor was the license mentioned anywhere.

**Comment by cesaramh** [comment]
These specifications are considered fundamental research.

**Comment by phoe** [comment]
"These specifications are considered fundamental research" does not allow me to use this code in my own projects because I do not know how this code is licensed. For example, is this code GPLv2?

https://github.com/nasa/pvslib/blob/d295bf81c9baa778db944960971cefc5c3d6043d/pvs-patches/patch-6.lisp#L5-L8

Or LGPLv2?

https://github.com/nasa/pvslib/blob/d295bf81c9baa778db944960971cefc5c3d6043d/TU_Games/tu_game.pvs#L189-L192

Or Microsoft Research License Agreement?

https://github.com/nasa/pvslib/blob/d295bf81c9baa778db944960971cefc5c3d6043d/MetiTarski/dist/Z3-LICENSE.txt#L1-L3

Or public domain?

https://github.com/nasa/pvslib/blob/d295bf81c9baa778db944960971cefc5c3d6043d/decimals/decimals.lisp#L7

So far it seems that each individual subfolder of this repository contains its own licensing information, which IMO should be mentioned in the toplevel README and overall clarified. This is because freely available code is useless for inclusion in other software projects unless it has a clear legal/licensing status.

Please reopen the issue since the provided answer does not solve the original problem.

**Comment by cesaramh** [comment]
This is a repository of formal developments witten in a formal specification language, called PVS. These developments are not to be included in “other software projects,” since they are not software. So, that notion doesn’t make sense. 

Most of these formal developments have been in the public domain for years and they were originally developed by NASA researchers. We still maintain them and re-prove them as new features of PVS become available. The developments with particular licenses belong to the contributors. The code you are pointing out are either patches to PVS or third party tools used in standalone mode by PVS proof strategies (posted with the permission of the developpers)

I’ll clarify this in the repository. 

Thanks for your interest,

--
Cesar

**Comment by phoe** [comment]
Thanks! This elaboration solves the issue.

**Comment by cesaramh** [comment]
Thanks. I apologize for the time I took to answer your issue. We are about to update the libray (branch pvs7.0) and it has better information about each contribution to the library (to best of our knowledge, some contributions are more than 25 years old). Fun fact: this library was featured in the movie The Martian, but we didn’t get the credits. 

--
Cesar
